---
- name: Add the user
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: "{{ user.shell | default('/usr/bin/bash') }}"
    password: "{{ user_password }}"
    uid: "{{ user.uid | default(omit) }}"
    groups:
      - wheel

- name: Add authorized_keys
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ user_authorized_keys }}"
